apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: services/phpmyadmin
          ports:
            - containerPort: 5000
              name: phpmyadmin
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          imagePullPolicy: IfNotPresent

---

  apiVersion: v1
  kind: Service
  metadata:
    name: phpmyadmin
    labels:
      app: phpmyadmin
  spec:
    ports:
      - port: 5000
        targetPort: 5000
        protocol: TCP
        name: phpmyadmin
    selector:
      app: phpmyadmin
      tier: mysql
    type: LoadBalancer